### ISSUE TITLE
A way to call :Pckr install synchronously

### ISSUE THREAD

**Issue by D4yvid** [lewis6991/pckr.nvim#12]
### Describe the feature

I tried a lot of ways of creating a 'sync' install, like lazy one, for example:

```lua
require 'pckr'.sync_install() -- Will block until all plugins were installed

require 'some.installed.plugin'.setup {}
```

**Comment by lewis6991** [comment]
Why do you need to install plugins synchronously?

**Comment by D4yvid** [comment]
I'm on a context where all functions need to be called in order, and it would be a nice thing to specify a `plugins` block and after it just configure the plugin. For example:

```
plugins {
  'foo/bar'
}

require 'bar'.setup {} -- Wouldn't error because that the plugin is already installed
```

**Comment by lewis6991** [comment]
You need to use `config` and dependencies.
