### ISSUE TITLE
How does :Pckr install know where the config is

### ISSUE THREAD

**Issue by benlieb** [lewis6991/pckr.nvim#13]
The documentation isn't clear to me. Where does this information come from? Does it look for a specific file in a specific location?

**Comment by lewis6991** [comment]
You as a user need to run `require('pckr').add(...)` in your `init.lua`.

I use this code to bootstrap it:

```lua
  local pckr_path = vim.fn.stdpath("data") .. "/pckr/pckr.nvim"
  vim.opt.rtp:prepend(pckr_path)

  if not vim.uv.fs_stat(pckr_path) then
    vim.fn.system({
      'git',
      'clone',
      '--filter=blob:none',
      'https://github.com/lewis6991/pckr.nvim',
      pckr_path
    })
  end

  require('pckr').add{...}
```

**Comment by benlieb** [comment]
@lewis6991 I assume you mean that it has to be "somewhere" in the require tree that is initiated by `init.lua`?

**Comment by lewis6991** [comment]
Yes
