### ISSUE TITLE
Don't works: "Error executing luv callback"

### ISSUE THREAD

**Issue by safocl** [lewis6991/pckr.nvim#2]
- `nvim --version`: `NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3`
- `git --version`: `2.41.0`
- Operating system/version: Archlinux
- Terminal name/version: Konsole

### Steps to reproduce
copy the lines of the configure in the nvim init.lua

### Actual behaviour
```
Error executing luv callback:                                                                                                                                              
...afocl/.local/share/nvim/pckr/pckr.nvim/lua/pckr/jobs.lua:26: attempt to call field 'system' (a nil value)
stack traceback:
        ...afocl/.local/share/nvim/pckr/pckr.nvim/lua/pckr/jobs.lua:26: in function 'fn_or_ret'
        ...focl/.local/share/nvim/pckr/pckr.nvim/lua/pckr/async.lua:30: in function <...focl/.local/share/nvim/pckr/pckr.nvim/lua/pckr/async.lua:7>
Press ENTER or type command to continue
```

### Expected behaviour
install and works

### packer files

<details>
<summary>packer log file</summary>

~/.cache/nvim/packer.nvim.log is not exist

</details>

<details>
<summary>packer compiled file</summary>

contents of `packer_compiled.vim` is not exist

</details>

**Comment by lewis6991** [comment]
`vim.system` is only available in nightly. The README needs to be updated.

**Comment by safocl** [comment]
> 

does this mean that pckr.nvim cannot be run on a non-nightly neovim?

**Comment by lewis6991** [comment]
Yes
