### ISSUE TITLE
How to deal with plugins with submodules?

### ISSUE THREAD

**Issue by Bastes** [lewis6991/pckr.nvim#50]
Hello :) very new to `pckr` and coming from `vim-plug`, so far it's mostly a smooth ride, but there is a use case that is currently broken and I'd like to address: the case for submodules.

I've inspected the history and noted support for submodules in plugins have been dropped, so I suppose there is a reason for that, but it so happens to break at least one plugin I'm using:
[GrzegorzKozub/vim-elixirls](https://github.com/GrzegorzKozub/vim-elixirls).

So here's me being curious as to why that support was dropped, and wondering whether an optional feature is feasable (ie an argument in the package config that tells the package manager to maintain the submodules when maintaining the plugin). This is not a case where the submodule is another vim plugin, this is a situation where the submodule is an lsp server that the package is tasked to install an keep up-to-date.

**Comment by lewis6991** [comment]
Can't you just add `run = 'git submodule update --init`?

Submodule support was dropped because it was too niche and I didn't want to support it. Submodules are bad in general anyway.

**Comment by Bastes** [comment]
Yeah, sure :) so, I take it the `run` option makes the commands run in the plugin's directory?

I'll be sure to offer a `pckr` install instruction to the `elixir-ls` repo if it works, too. Thank you for your reply :)

**Comment by Bastes** [comment]
Ah, one other question if I may: I already have a `run = ':ElixirLsCompileSync'` section in the plugin's line ; how do I add the git command on top of that?

**Comment by lewis6991** [comment]
Maybe:
```lua
run = function()
   vim.fn.system('git submodule ...')
   vim.cmd('ElixirLsCompileSync')
end
```

**Comment by Bastes** [comment]
Ah, yeah, now I get why the function option is interesting :) thanks a lot, I'll try that asap.

**Comment by Bastes** [comment]
Hmm... I just tried this:
```lua
-- ...
require('pckr').add{
  -- ...
  { 'GrzegorzKozub/vim-elixirls', run = function()
    vim.fn.system('git submodule update --init')
    vim.cmd('ElixirLsCompileSync')
  end};
  -- ...
}
```

But it didn't work. The command `git submodule update --init` didn't seem to produce anything (the submodule directory remained empty), and the install fails saying the `'ElixirLsCompileSync'` vim command did not exist either.

I don't know what I'm missing here.

I tried doing those commands manually (going into the plugin's directory and gooing `git submodule update --init` did check out the code, then starting `nvim` and using `:ElixirLsCompileSync` worked fine apparently.

**Comment by lewis6991** [comment]
You might need to uninstall the plugin first as `run` is only triggered on install and updated.

**Comment by Bastes** [comment]
That's how I tried, a couple of time, checking whether the directory had been removed after the `:Pckr clean` command.

**Comment by Bastes** [comment]
Ok, I think I've got it for the submodule ; tried this:

```lua
run = function()
  vim.fn.system('pwd > /tmp/vim-elixirls.log')
  vim.fn.system('git submodule update --init >> /tmp/vim-elixirls.log')
  vim.cmd('ElixirLsCompileSync')
end
```

What I found in the `/tmp/vim-elixirls.log` file was:
```
/Users/myaccount/.local/share/nvim/site/pack/pckr/opt
```
So, the system commands are executed in `pckr/opt` and not in the plugin's directory, so I guess I just have to change the working directory and that should go better for the submodule command.

Now to figure out why the plugin's command is not there and we should be cooking :)

**Comment by Bastes** [comment]
So, doing this:
```lua
  { 'GrzegorzKozub/vim-elixirls', run = function()
    vim.cmd('cd vim-elixirls')
    vim.fn.system('git submodule update --init')
    vim.cmd('cd ..')
    vim.cmd('ElixirLsCompileSync')
  end};
```
Works!... well, it checks out the submodule. The `'ElixirLsCompileSync'` command is still mia.

Is it normal? I thought the `run` function would run once the plugin is already loaded or something? Do note that the command works as soon as `nvim` is subsequently started, so it's not something like the submodule is not made available at all.

**Comment by lewis6991** [comment]
In the code we have:

```lua
  if plugin.run or plugin.start then
    async.schedule()
    local loader = require('pckr.loader')
    loader.load_plugin(plugin)
  end

  if not plugin.run then
    return
  end

  async.schedule()

  local run_task = plugin.run
  
  ...
```

So we explicitly load the plugin if it has `run`, however `loader.load_plugin()` will not source `plugin/*` (which contains `ElixerCompileSync`) if Nvim is currently within the "sourcing init.lua" stage of its startup sequence.

However, I believe `async.schedule()` should wait for this, which means in this block `loader.load_plugin(plugin)` should always source `plugin/*`.

**Comment by Bastes** [comment]
Yeah, that's what I'd think should happen. Also, for other plugins the `run` seems to work well (none of my other plugins have a function for their `run` option).

So, I'm going to try and make a function for the other `run`-able plugins and see whether they have the same problem, just in case :) thank you for your support so far, and if we discover a bug I'll try and provide whatever I can to help fix it ;)

**Comment by Bastes** [comment]
Hmm... well, I tried de-activating one of my other plugins, `:Pckr clean` then re-launching nvim and letting it install... and guess what, the command in the `run` section also is mia!

Maybe I've stumbled upon a bug?

**Comment by Bastes** [comment]
For ref, this is the other plugin I cleaned-reinstalled:
```lua
  { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' };
```

Once it's installed, I can run the `:TSUpdate` command and it works fine.

**Comment by lewis6991** [comment]
Well this is the full code:

```lua
  local run_task = plugin.run

  if type(run_task) == 'function' then
    disp:task_update(plugin.name, 'running post update hook...')
    local ok, err = pcall(run_task, plugin, disp)
    if not ok then
      return 'Error running post update hook: ' .. err
    end
  elseif type(run_task) == 'string' then
    disp:task_update(plugin.name, string.format('running post update hook...("%s")', run_task))
    if vim.startswith(run_task, ':') then
      -- Run a vim command
      local ok, err = pcall(vim.cmd --[[@as function]], run_task:sub(2))
      if not ok then
        return 'Error running post update hook: ' .. err
      end
    else
      local jobs = require('pckr.jobs')
      local jr = jobs.run(run_task, { cwd = plugin.install_path })

      if jr.code ~= 0 then
        return string.format('Error running post update hook: %s', jr.stderr)
      end
    end
  end
```

In either case it is just running `pcall`.

**Comment by Bastes** [comment]
Ok :)

So far I've tested on a macos computer (work) and I'll probably have a go tonight on a linux (ubuntu / home) just to confirm the symptoms. My `pckr` install is fresh from yesterday, I've switched because I was advised to do so from `vim-plug`.
