### ISSUE TITLE
Fresh install seems to be broken. Full `$XDG_DATA_HOME/nvim` wipe gets pckr to install nothing.

### ISSUE THREAD

**Issue by DrKJeff16** [lewis6991/pckr.nvim#7]
- `nvim --version`:
    ```
    NVIM v0.10.0-dev-1282+g5f4f83ba3
    Build type: Release
    LuaJIT 2.1.1695653777
    ```
- `git --version`: `2.42.0`
- Operating system/version: `Manjaro Linux  KDE`
- Terminal name/version: [`st-0.9`](https://st.suckless.org)

### Steps to reproduce
1. Convert all packages I used to manage with Packer, sticking exclusively to the syntax provided in the [`README.md`](https://github.com/lewis6991/pckr.nvim/blob/main/README.md).
2. Wipe `$XDG_DATA_HOME/nvim` (`$HOME/.local/share/nvim`) to get fresh install.
3. Start nvim. Get my own warnings as expected.
4. `:Pckr install`

### Actual behaviour
`[pckr.nvim[INFO  21:39:07] actions.lua:327: All configured plugins are installed`.
Yet none of my packages are cloned, let alone installed and loaded.

### Expected behaviour
My packages to be installed...

### pckr files

<details>
<summary>Plugin specification file(s)</summary>

[abstract_setup.zip](https://github.com/lewis6991/pckr.nvim/files/12812138/abstract_setup.zip)

_This includes my `init.lua`, `lua/pckr.lua` and `lua/pckr_ref.lua`. You can check it using `unzip -l <file>`._ The latter file is for my pending files to convert.
</details>

**Comment by lewis6991** [comment]
Seems to work fine for me. Your pckr file has a bunch of problems but that doesn't stop it from cloning the plugins.

**Comment by lewis6991** [comment]
No response, closing.
