### ISSUE TITLE
System wide install

### ISSUE THREAD

**Issue by ghost** [lewis6991/pckr.nvim#9]
### Describe the feature

Hello,

packer.nvim supported working from a system wide install. This is enabled the system operator to configure Neovim on hosts with some minimal amount of Neovim packages installed alongside it, including Packer. The aim to reduce clutter in user's ${HOME} directories, and keep packages, and their state in sync with system installed Neovim.

Attempting to do the same with pckr.nvim results in the package not loading, the help is available, but Neovim cannot find the pckr module itself.

Is this possible? Am I installing pckr into the wrong location?
I install pckr.nvim to /usr/local/share/nvim/site/pack/pckr/start/pckr.nvim.

**Comment by lewis6991** [comment]
I don't know what this means or how packer.nvim supported this, or why packer.nvim was required to support it.

If you want to provide system plugins, install them somewhere and ask users to modify their rtp accordingly.
